added badge repo and verification
starcraft66/lanparty-seating pull request #59
Opened 2023-08-06 16:47 UTC by luxor37

@starcraft66 tu verifieras la migration pour generate la badge table proprement

2023-08-07 04:30 UTC, starcraft66 requested changes
Looks good, faut juste swapper le `uid` et le `serial_key` dans la logique, car le `uid` c'est le code dans le badge nfc et l'autre valeur serait les 6 chiffres sur le badge.

2023-08-09 05:49 UTC, AXDOOMER requested changes
* Dans la page "self sign" que je suggère de renommer "self service", quand j'entre mon numéro de badge (e.g. E00403530ABE133F), rien ne se passe quand je clique le bouton vert. 
Le error handling est absolument nécessaire ici pour diagnostiquer les problèmes. Je sais pas pourquoi ça marche pas, j'assume que ça a été testé et que ça fonctionnait. Pourtant j'ai migré la BD et repopulé avec le data, donc y'a sûrement de quoi de broken, mais pas le moyen de savoir c'est quoi car y'a pas d'erreur affichées dans le front-end. 

* Dans la page des cancellations, si je clique sur un poste bleu, ça me demande "Do you want to close this station?", mais quand je clique sur le bouton vert, ça fait rien. Faut que je reload la page pour voir le changement et enlever le modal. Même chose lorsque je veux réouvrir la station. 

Je peux pas faire plus de tests comme les réservations sont broken.

2023-08-09 05:58 UTC, AXDOOMER commented
Closes https://github.com/starcraft66/lanparty-seating/issues/45

2023-08-10 20:24 UTC, starcraft66 approved these changes
LGTM

2023-08-10 20:45 UTC, AXDOOMER approved these changes
ok

2023-08-10 20:47 UTC, merged